# copied from story-indexer
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
  - repo: http://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: http://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      # run mypy via wrapper to make sure "pre-commit" optional
      # dependencies in pyproject.toml installed (to keep DRY).
      - id: mypy
        entry: ./.pre-commit-run.sh mypy
        additional_dependencies: ["pip>=22.0"]
        # without implicit --ignore-missing-imports:
        args: [--strict]
  - repo: http://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: http://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
